type EcwidApiResponse<ItemType> = {
  count: number;
  items: Array<ItemType>;
  limit: number;
  offset: number;
  total: number;
};

export type Categories = EcwidApiResponse<Category>;

export type Category = {
  id: number;
  orderBy: number;
  name: string;
  nameTranslated: {
    nl: string;
  };
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  description: string;
  descriptionTranslated: {
    nl: string;
  };
  enabled: boolean;
  isSampleCategory: boolean;
  seoTitle: string;
  seoDescription: string;
  alt: {
    main: string;
  };
};

export type Products = EcwidApiResponse<Product>;

export type Product = {
  id: number;
  sku: string;
  thumbnailUrl: string;
  unlimited: boolean;
  inStock: boolean;
  name: string;
  price: number;
  priceInProductList: number;
  defaultDisplayedPrice: number;
  defaultDisplayedPriceFormatted: string;
  tax: {
    taxable: boolean;
    defaultLocationIncludedTaxRate: number;
    enabledManualTaxes: [];
    taxClassCode: string;
  };
  lowestPrice: number;
  defaultDisplayedLowestPrice: number;
  defaultDisplayedLowestPriceFormatted: string;
  lowestPriceSettings: {
    lowestPriceEnabled: boolean;
  };
  isShippingRequired: boolean;
  hasFreeShipping: boolean;
  weight: number;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  created: string;
  updated: string;
  createTimestamp: number;
  updateTimestamp: number;
  productClassId: number;
  enabled: boolean;
  options: Array<{
    type: string;
    name: string;
    nameTranslated: {
      nl: string;
    };
    choices: Array<{
      text: string;
      textTranslated: {
        nl: string;
      };
      priceModifier: number;
      priceModifierType: string;
    }>;
    defaultChoice: number;
    required: boolean;
  }>;
  fixedShippingRateOnly: boolean;
  fixedShippingRate: number;
  shipping: {
    type: string;
    methodMarkup: number;
    flatRate: number;
    disabledMethods: [];
    enabledMethods: [];
  };
  defaultCombinationId: number;
  imageUrl: string;
  smallThumbnailUrl: string;
  hdThumbnailUrl: string;
  originalImageUrl: string;
  originalImage: {
    url: string;
    width: number;
    height: number;
  };
  borderInfo: {
    dominatingColor: {
      red: number;
      green: number;
      blue: number;
      alpha: number;
    };
    homogeneity: boolean;
  };
  description: string;
  galleryImages: Array<{
    id: 1;
    url: string;
    thumbnail: string;
    originalImageUrl: string;
    imageUrl: string;
    hdThumbnailUrl: string;
    thumbnailUrl: string;
    smallThumbnailUrl: string;
    width: number;
    height: number;
    orderBy: number;
    borderInfo: {
      dominatingColor: {
        red: number;
        green: number;
        blue: number;
        alpha: number;
      };
      homogeneity: boolean;
    };
  }>;
  media: {
    images: Array<{
      id: string;
      isMain: boolean;
      orderBy: number;
      image160pxUrl: string;
      image400pxUrl: string;
      image800pxUrl: string;
      image1500pxUrl: string;
      imageOriginalUrl: string;
    }>;
    videos: [];
  };
  categoryIds: Array<number>;
  categories: Array<{
    id: number;
    enabled: boolean;
    name: string;
    nameTranslated: string;
  }>;
  defaultCategoryId: number;
  seoTitle: string;
  seoDescription: string;
  attributes: [];
  relatedProducts: {
    productIds: [];
    relatedCategory: {
      enabled: boolean;
      categoryId: number;
      productCount: number;
    };
  };
  combinations: [];
  volume: number;
  showOnFrontpage: number;
  isSampleProduct: boolean;
  googleItemCondition: string;
  isGiftCard: boolean;
  discountsAllowed: boolean;
  nameYourPriceEnabled: boolean;
  compositeComponents: [];
  compositeParents: [];
};
